### ISSUE TITLE
Additional context menu options for tab selections

### ISSUE THREAD

**Issue by Bill13579** [Bill13579/tabby#100]
Additional context menu options for tab selections in the tabs list:

- [x] Load/Unload
- [x] Reload
- [x] Sending tabs to different windows
- [x] Sending tabs to a new window
- [ ] Copy

**Comment by roykeek** [comment]
I support adding to contextual menu (rightClick the tab)

- [ ] Sending tabs to different windows
- [ ] Sending tabs to a new window

Thank you for developing tabby!

**Comment by Bill13579** [comment]
Last of it added in 23cba2025f7c706a6451ad4f21603e64632d4b9a
