### ISSUE TITLE
Tabby settings loaded on the fly causing draw delay

### ISSUE THREAD

**Issue by eberhardweber** [Bill13579/tabby#107]
Currently, when opened, Tabby seems to load user settings for "popup size" and "popup scale" only after drawing the actual popup. The default settings seem to be loaded first, after which Tabby pulls the user settings and then resizes the popup.

With a vast amount of open browser windows and tabs (the intended purpose for Tabby!), however, it takes several seconds for the default Tabby popup to morph into its set proper size and scale. 

This creates a jarring effect where the popup box morphs from one size and scale to another after it becomes reactive.

**Comment by Bill13579** [comment]
This should be fixed in 39b5823f5ab37896a84af45a8b2ecc3e3265549c and will land in the next update `:)`
