### ISSUE TITLE
Add keyboard shortcuts to enable keyboard only navigation

### ISSUE THREAD

**Issue by barmic** [Bill13579/tabby#11]
If we have a shortcut to 

* open the tabby window (with focus on filter)
* open the tabby window (with focus on first tab)
* select a tab with up and dow arrow
* go to selected tab with "enter"
* close selected tab with "delete"

We can have a keyboard only navigation !

**Comment by Bill13579** [comment]
Thanks for the suggestion. I think a keyboard only navigation is great!
I am planning to add this feature for Tabby v1.2. Now if you can suggest some keyboard shortcuts, I will be happy to use it.

These are the shortcuts that I plan to add:
- Open the Tabby window (with focus on filter)
- Open the Tabby window (with focus on current tab in the current window)
- Select a tab with up and down arrows
- Select a window with "ctrl+up" and "ctrl+down" keyboard shortcuts
- Go to selected tab with "enter"
- Close selected tab with "delete"

**Comment by barmic** [comment]
Sorry I totally forgot this request:

IMHO:

- Open the Tabby window (with focus on filter) → Alt + f (filter)
- Open the Tabby window (with focus on current tab in the current window) → Alt + c (current)
- Select a tab with up and down arrows → Alt + ↑ or ↓ (or j/k)

I'm ok for the rest.

**Comment by Bill13579** [comment]
Great! I'm working on it.

**Comment by bartol** [comment]
Any updates on this issue?

**Comment by campbellkerr** [comment]
I've been using Workspaces for Firefox add-on which has a Ctrl+Space hotkey to open the list of tabs. After hitting Ctrl+Space the search bar/filter bar is highlighted.

https://github.com/moosingin3space/wksp-for-firefox

The development seems to have stopped, in fact I logged a feature request to use DEL to close a tab:
https://github.com/moosingin3space/wksp-for-firefox/issues/11

Tabby is way faster to open than Workspaces so I'm hoping this hotkey stuff gets implemented soon!

**Comment by Bill13579** [comment]
Thank you everyone who contributed to this issue; keyboard only navigation has been fully implemented in the development branch! It will land on v2.1, but you can try it out right now by cloning this repo and switching to the v2.1 branch, and then installing it.

**Comment by Bill13579** [comment]
### Final keyboard shortcuts
`Alt+X`: Open Tabby with focus on search
`Alt+C`: Open Tabby with focus on current tab
If you tap `Enter` while focused on the search bar, the first result will get focused
Use `Up` and `Down` to scroll through tab list
If you tap `Enter` while focused on a tab, you can go to that tab
`Delete` to close a tab

**Comment by Bill13579** [comment]
### Update
New shortcuts!
`M` to mute a tab
`P` to pin a tab
