### ISSUE TITLE
Add ability to rename a window

### ISSUE THREAD

**Issue by Bill13579** [Bill13579/tabby#12]
A lot of users have requested the ability to rename a window. I think this feature can help group tabs, so it will definitely be added in Tabby v1.2!

If you have any suggestions on how to implement this feature, please feel free to comment down below.

**Comment by Bill13579** [comment]
Added in v2.1-dev. Expect this to be in version 2.1

**Comment by skyerjoe** [comment]
Is this still implemented ?  

best regards
