### ISSUE TITLE
The "Everything new in Tabby 3.0" tab opens up with every restart

### ISSUE THREAD

**Issue by eberhardweber** [Bill13579/tabby#123]
In 3.0.1, the "what's new" tab (re)opens with every browser restart. 

I think once per update would make more sense, preferably with a toggle to turn off in the settings.

**Comment by Bill13579** [comment]
Solved, will be included in the next update.

**Comment by zesty** [comment]
so, release it?

**Comment by zesty** [comment]
Still happening.

**Comment by Zobbster** [comment]
Can confirm, this is still happening. There's no settings to allow me to toggle this behavior, that I can see.
