### ISSUE TITLE
Tabby strict_min_version – and requirements at addons.mozilla.org (AMO)

### ISSUE THREAD

**Issue by grahamperrin** [Bill13579/tabby#13]
From <https://github.com/Bill13579/tabby/issues/1#issuecomment-381775417>: 

> … can only work on Firefox 59 and above. …

Currently at https://addons.mozilla.org/addon/tabby-window-tab-manager/ and https://addons.mozilla.org/addon/tabby-window-tab-manager/versions/ it appears as if the extension is compatible with inferior versions of browsers. 

Consider: 

- adding a `strict_min_version` to `manifest.json` 
- rationalising the AMO pages for the extension. 

Thanks 👍

**Comment by Bill13579** [comment]
Thanks for the bug report! I have added `strict_min_version` to the `manifest.json` file in the `v2.0-dev` branch.
