### ISSUE TITLE
The "Everything new in Tabby 3.0" tab opens up with every restart

### ISSUE THREAD

**Issue by zesty** [Bill13579/tabby#149]
https://github.com/Bill13579/tabby/wiki/Everything-new-in-Tabby-3.0

**Comment by paulius-valiunas** [comment]
same here, seems like every browser update triggers this. At first I thought it was showing me the changelog after every update of the extension, but the page doesn't include any minor or patch versions so that doesn't make sense.

**Comment by Zobbster** [comment]
I've been holding off on replying/posting about this topic for months, but it's absolutely doing my head in now. Please can we have an option to stop this behavior?

**Comment by TrueBeastEmperor** [comment]
Same problem here.

**Comment by Bill13579** [comment]
Should be fixed with the new update, reopen if it's still happening.
