### ISSUE TITLE
Search tabs box should be focused

### ISSUE THREAD

**Issue by JonasNo** [Bill13579/tabby#17]
When you click the tabby icon the search tabs box should be focused so you can start search immediately.
FIX:
File: tabby/src/popup/index.html
Line: 34
Change this:
`<input id="search" type="text" placeholder="Search Tabs" />`
to this:
`<input id="search" type="text" placeholder="Search Tabs" autofocus />`

**Comment by Bill13579** [comment]
Thanks for the feature request! Actually, this feature is already implemented in the dev branch of Tabby. Not only that, I have introduced Smart Search to Tabby. These will all be included in Tabby v2.0.
