### ISSUE TITLE
Take too much time to load tabs on Firefox

### ISSUE THREAD

**Issue by XOR-op** [Bill13579/tabby#194]
Using tabby v3.1 on Firefox, I found that opening tabby (either by clicking icon or by shortcut) waits too long to load tabs. I estimate the loading time is ~500ms with manual timer. However on Chrome v2.0.3, I don't see this issue from happening. Tabs are instantly loaded and I cannot feel the loading at all.

I tried to turn off "Show tab details" and "Show tab previews", but turning them off doesn't help. I also don't think it's a problem related to the count of opened tabs, because I got the same issue with only 5 tabs opened in 1 window.

Since you don't provide older version of tabby, I cannot test other versions. Could you provide some signed older versions, or tell me if you encountered similar problem?

Update: From mozilla's addon history, I tried different older versions. Downgrading to 3.0 significantly reduces the load time while it's still noticable. Downgrading to 2.11 makes the load time unnoticable.

**Comment by johny65** [comment]
I'm using Tabby for the first time and have the same issue, every time I open Tabby popup it takes 3 seconds to load my opened tabs (less than 10 tabs).

**Comment by Bill13579** [comment]
Fixed in 9a4e7737613037c6e9ca89c107c3178e9d3f220c and will land in the next release!
