### ISSUE TITLE
Alt/Option + f8  ; No option to choose if popup/sidebar/separate_tab ; Just cycles between

### ISSUE THREAD

**Issue by roshanpoduval** [Bill13579/tabby#199]

**Comment by Bill13579** [comment]
Once you cycle between, using the Ctrl+Shift+Space and Ctrl+Shift+X shortcuts for opening Tabby will open Tabby in the current layout. You can also map these shortcuts differently: https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox
