### ISSUE TITLE
Blank tab list

### ISSUE THREAD

**Issue by rayman89** [Bill13579/tabby#2]
No tab appears when I press the extension button so I cant do anything. Any idea why?

**Comment by Bill13579** [comment]
What environment are you in (browser, browser version, operating system)? Also, can you can take a screenshot of the popup?

**Comment by rayman89** [comment]
I found the problem. Recently seems that changing  browser.sessionstore.max_tabs_undo to be more than 10 fucks up addons that list tabs or restore closed tabs.
