### ISSUE TITLE
Right Click in fire fox doesn't let me move tabs

### ISSUE THREAD

**Issue by IdirisDT** [Bill13579/tabby#205]
Prior to the update I could right click on a tab and it would allow me to move the tab to another window, but now it doesn't. Did I miss something in the update notes?

**Comment by Bill13579** [comment]
Yeah I think I know why this is, will be fixed in the next patch!

**Comment by Bill13579** [comment]
I also improved the implementation a bit, it should now work for multiple tabs selected too. All of this should land in 3.2.1

**Comment by IdirisDT** [comment]
When will it be released?

**Comment by Bill13579** [comment]
Ah well I just submitted it but the last release took a week to be approved lmao
