### ISSUE TITLE
Tabby overriding ALT commands in Firefox 75.0

### ISSUE THREAD

**Issue by McBobb** [Bill13579/tabby#27]
This may be due to Mozilla doing something stupid in today's release of Firefox 75.0, but Tabby has started usurping the functions of my ALT key; specifically, when using it to enter 4-digit ALT+ codes to access extended ASCII characters.

With Tabby active, holding ALT and then hitting any key in the numpad causes Firefox to jump back to the previous tab, and continuing to type the 4-digit code does nothing.

This addon is fantastic, and I hope this can be addressed.

My Firefox troubleshooting information is in the file attached

[Firefox Troubleshooting Info.txt](https://github.com/Bill13579/tabby/files/4549818/Firefox.Troubleshooting.Info.txt)

**Comment by Bill13579** [comment]
Sorry for any inconveniences; can you respond with your Operating System, as well as if you are using the dev. or the stable version? ( probably the stable version, but I just wanted to make sure :) ).

**Comment by Bill13579** [comment]
I think it's the keyboard shortcuts (Alt+1 and Alt+2) that are causing these issues.
Although, we would also need to then change the keyboard shortcuts for MacOS to fit the new keyboard shortcuts.

**Comment by Bill13579** [comment]
### Update June 18
Open last used tab: This has been changed from `Ctrl/Alt+1` to `Ctrl+Shift+L`
Open last used tab: This has been changed from `Ctrl/Alt+2` to `Ctrl+Shift+0`
