### ISSUE TITLE
Show Tab Preview is unavailable!

### ISSUE THREAD

**Issue by tingfangyeh** [Bill13579/tabby#28]
The option is grey and I cannot switch it on!
Please fix it, thank you!
![05-21-2020-17 20 15](https://user-images.githubusercontent.com/19425690/82538866-5b20fc00-9b87-11ea-95f3-fa1f3652b00c.jpg)
PS: I am using Chrome add-on.

**Comment by Bill13579** [comment]
Hi @tingfangyeh ! Chrome unfortunately doesn't support the APIs necessary (specifically, https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/captureTab) for showing tab previews at this time, so Tabby won't be able to show previews unless a workaround is found. But, in the case that someone finds a workaround, I am happy to merge it in to the dev branch!
