### ISSUE TITLE
[not an issue] Simple question: Increase the height of the popup to more than 600px

### ISSUE THREAD

**Issue by EstherMoellman** [Bill13579/tabby#29]
Hi,

Firstly thank you for Tabby.

Please, I have a simple question: At the options is possible to customize the "popup" size. But how can I increase the pop-up height over 600px?

Thank you

**Comment by Bill13579** [comment]
Hi @EstherMoellman! The reason that the height is limited to 600px, is that Firefox (and fyi. Chrome too) limits the size of popups to 800x600px. So unfortunately, it is a limit imposed by the browser which I cannot work around. But I do get this question a lot; thanks for asking!
