### ISSUE TITLE
Preferences to tabby is hidden

### ISSUE THREAD

**Issue by iliekprogrammar** [Bill13579/tabby#33]
### Problem
Although you can [access](https://i.ibb.co/pQ8Dh5x/Screenshot-20200626-213649.png) it in add-ons manager, it pretty hidden.  
There's probably some users that never would've known about this at all.

### Suggestion
Add a button in tabby to manage the user's preferences.

**Comment by Bill13579** [comment]
@iliekprogrammar Thanks for the suggestion! I completely agree that the current settings page is waaaaaaaaaay too hidden. I actually just pushed out version 2.1 a few hours ago which along with new features also addresses this issue, and it should start to slowly roll out over the next few days. There's now a clearly defined settings button right beside the search bar.
