### ISSUE TITLE
Middle-clicking on a tab should close it

### ISSUE THREAD

**Issue by dkter** [Bill13579/tabby#42]
Just like it does in the tab bar.

**Comment by Bill13579** [comment]
Done!

**Comment by jpoles1** [comment]
For some reason this seems like it may have broken. When I middle mouse click my Tabby simply opens up the middle mouse scroller (see below) instead of closing the tab:

![image](https://github.com/Bill13579/tabby/assets/366282/fb00f860-947a-4fe4-9922-eb26b0e7037a)
