### ISSUE TITLE
[Enhancement] hovering over an unloaded tab should have a placeholder preview

### ISSUE THREAD

**Issue by campbellkerr** [Bill13579/tabby#43]
Currently, if I hover over a tab that's loaded, then an unloaded one, the preview of the loaded tab remains. Ideally it should just be blank or "no preview available" etc. For example I have unloaded tabs after a session restore.

Loaded tab (excel online):
![image](https://user-images.githubusercontent.com/38451588/86003562-51779780-ba55-11ea-89ca-1ff03035464f.png)

Unloaded youtube tab - preview and link still shows the previous excel online one:
![image](https://user-images.githubusercontent.com/38451588/86003728-913e7f00-ba55-11ea-8729-696e1d65a4b9.png)

**Comment by Bill13579** [comment]
@campbellkerr I agree that unloaded tabs should show nothing instead of just keeping that last tab's details. I'll try to push this in to Tabby by v2.1.1

**Comment by Bill13579** [comment]
<img width="414" alt="Screen Shot 2020-07-16 at 10 48 25" src="https://user-images.githubusercontent.com/35489013/87704878-e36be980-c751-11ea-93c7-bce7504f4e62.png">

**Comment by Bill13579** [comment]
<img width="415" alt="Screen Shot 2020-07-16 at 10 49 12" src="https://user-images.githubusercontent.com/35489013/87704935-fd0d3100-c751-11ea-9e2b-646a1b828a16.png">

**Comment by Bill13579** [comment]
Now when previewing an unloaded tab, Tabby will show a blank image along with a button to reload the tab!
