### ISSUE TITLE
[Enhancement] Arrow keys should be able to navigate tab list

### ISSUE THREAD

**Issue by campbellkerr** [Bill13579/tabby#44]
Unless i'm doing something wrong?

- Press Ctrl+Shift+Space to bring up Tabby
- Up/down arrow keys are unable to navigate the list (unable to select a tab via keyboard)

Thanks!

**Comment by Bill13579** [comment]
@campbellkerr Ctrl+Shift+Space actually brings up Tabby with focus on the search bar, which means that hitting `Enter` should select the first result. Or in the case that you haven't searched for anything, select the first tab in the list! Hope this helps!

**Comment by Bill13579** [comment]
P.s., Ctrl+Shift+X will bring up Tabby with the focus instead on the current tab, which might be better suited in this case

**Comment by campbellkerr** [comment]
Thanks for the tip! Let me know if you want me to create a new issue? My use case is for when I have multiple tabs matching the search criteria - while Enter will select the top one, there's no keyboard way to select a different one (you'd have to type more matching characters into the search:

![image](https://user-images.githubusercontent.com/38451588/87219039-63353500-c39b-11ea-9252-b66863eacc66.png)

**Comment by Bill13579** [comment]
After pressing `Enter` and Tabby selects the first tab result, can you try the up and down arrows and see if that works? If not, this must be a bug.

**Comment by campbellkerr** [comment]
Thanks - using Enter does in fact work.
