### ISSUE TITLE
Keyboard shortcut conflict with Bitwarden addon

### ISSUE THREAD

**Issue by druxstr** [Bill13579/tabby#58]
On Firefox, installing both Tabby and Bitwarden (password manager, 160K users) breaks Bitwarden's autocomplete shortcut.

Bitwarden uses `Ctrl + Shift + L` for password autocompletion.

When Tabby's installed, `Ctrl + Shift + L` stops doing so.

Instead it makes you go to the last tab (similar to `Ctrl+9`).

If you use `Ctrl + Shift + L` a second time, it brings you back to the tab you were at first.

Removing Tabby solves the problem, but prevents you from using Tabby when Bitwarden's installed.

**Comment by Bill13579** [comment]
If you follow [these](https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox) instructions you should be able to change the shortcut to something else to avoid the collision. See #85 for details. Hope it helps!
