### ISSUE TITLE
Option/Keyboard Shortcut to close all filtered tabs in Tabby

### ISSUE THREAD

**Issue by McBobb** [Bill13579/tabby#64]
This is a fabulous addon, but I'm constantly frustrated by having to go down filtered lists of opened tabs to click each "X" for each tab I want to close from the same site. Is there a Keyboard command to close all filter result tabs? If not, there really, really needs to be!

**Comment by Bill13579** [comment]
If you press `A` (in the new update) it will now select all filtered/visible tabs (yay multiselect!) and then clicking the close button as usual will allow you to close all of them :)
