### ISSUE TITLE
How do I rename a window?

### ISSUE THREAD

**Issue by paulri** [Bill13579/tabby#68]
I just installed this extension on Waterfox (Windows 10). What I'd like to do is open up different windows, and from the taskbar preview that I see when my cursor hovers over the taskbar, see different names for each Waterfox window that I have open. I was able to click on the Tabby icon on the toolbar, and it has a new name, but Windows doesn't appear to realize this. 

Is there another step I need to take, to get this window renamed so I can see the name when I view the thumbnail preview from the taskbar?

**Comment by patrick-motard** [comment]
As far as I know the names you give to individual firefox windows in tabby are only stored in tabby. The names are not accessible to Windows, so you will not see the names in the Windows 10 task bar when hovering over each window preview.

**Comment by Bill13579** [comment]
The names are now accessible to windows 1db0188fe3368bbc31fea67754b3be3da10209b9
