### ISSUE TITLE
An extension, Firefox Multi-Account Containers, requires Container Tabs.

### ISSUE THREAD

**Issue by FibroJedi** [Bill13579/tabby#69]
Heya,

So I've just tried to get Tabby working, though a few things are not as intuitive as I hoped. But if I can wrap my head around it, all should be good.

1. "An extension, Firefox Multi-Account Containers, requires Container Tabs.": I'm getting this notice _despite the fact I have Container Tabs extension in and active_. Do I just ignore this notice?

2. I've now moved various groups of tabs to windows. When I close two windows, how do I reopen the specific one by name? I'm a bit reluctant to close one then lose it all until I understand it.

Thanks - neither are likely a bug, but I'd like to understand it better. Thank you.

**Comment by Bill13579** [comment]
1. Huh, I'm not too sure why containers is doing that.. its never asked me for another extension to use it before. The only thing I can possibly think of is maybe it's your FF version?

2. That's not a feature of Tabby's yet, but Firefox will by default save 3 closed windows: [link](https://support.mozilla.org/no/questions/1258487) You can go to the history view to use it (I actually didn't know this feature existed, it's pretty convenient! :D) <img width="381" alt="Screen Shot 2022-08-01 at 19 53 21" src="https://user-images.githubusercontent.com/35489013/182281706-c1e5760a-00f1-4f6f-94b3-6d3d44f7c187.png">
