### ISSUE TITLE
Don't load site icon for incognito tabs

### ISSUE THREAD

**Issue by jscher2000** [Bill13579/tabby#7]
To prevent private window site icons from being stored in the regular cache, it would be preferable not to load them in the popup. You could use null or with a little more work, replace them with a mask icon (for example, https://design.firefox.com/icons/viewer/ under the "General" category).

There seem to be a couple places in popup.js where you retrieve favIconUrl. In one case, it's in the context of tab so you can easily determine whether it's incognito. I didn't try to track down the one in the message handler.

Ref. https://discourse.mozilla.org/t/context-of-inline-image-requests-in-extension-page-e-g-a-popup/27932

**Comment by Bill13579** [comment]
Thanks for reporting this bug. I may have a solution for this problem. The technical details of this solution is down below. I will be opening a pull request soon.
### Details:
Steps to getting the favicon:
1. Request the favicon using XmlHttpRequest
--- When the parent window is in incognito mode, set the header "Cache-Control" to "no-store"
2. Set response type to "arraybuffer"
3. Convert the response into base64 string
4. Display the image.

Note: When a URL starts with "chrome://", it will be a local file, so no request is needed.

**Comment by jscher2000** [comment]
Great, thanks much.
