### ISSUE TITLE
Scrolling on mac is very difficult

### ISSUE THREAD

**Issue by cbiggins** [Bill13579/tabby#72]
Scrolling through the tabs on a mac in FF 86 is very jumpy and sometimes doesn't work at all.

Tried Macbook trackpad, external Apple trackpad and external mouse. 

Ambiguous issue I know, sorry, but I'm not sure what else I can add.

**Comment by IdeasMX01** [comment]
I have that problem too. I have more than 15 tabs opened, and I can only see 7, i can't scroll down to see the others.

**Comment by wsmwk** [comment]
@cbiggins, @IdeasMX01,

Do you still see this problem when using a current verison of Firefox and macOS?

I don't see this when using FIrefox 102 beta and macOS 12.4.
Perhaps this is related to version of macOS?

**Comment by Bill13579** [comment]
@wsmwk It might be, I can reproduce this on Catalina. It should be alleviated with the update
