### ISSUE TITLE
Re: tabby

### ISSUE THREAD

**Issue by Fenderfubs** [Bill13579/tabby#80]
Hi thee, firstly this not a bug fix request, rather if possible a how to manual for someone that is just trying to get control of my never ending tabs.
I don't wish to try to code anything, I just wish to add some categories, and or rename some.

If this is not too much work, I would be over the moon.

Thank you very much,
Fenderfubs

**Comment by patrick-motard** [comment]
@Fenderfubs is [this](https://github.com/Bill13579/tabby/wiki/Everything-new-in-Tabby-2.1) helpful?
