### ISSUE TITLE
Don't close popup after destroying a window

### ISSUE THREAD

**Issue by pmetzger** [Bill13579/tabby#83]
When you destroy a complete window inside the popup, either by killing its last tab or by killing the whole thing, the popup goes away. This is very annoying if you're trying to clean up a very large number of windows; it forces you to open the popup again and then scroll to the part of the list of the list where you're doing your work again. (Some people are crazy enough to have really huge numbers of windows.)

It would be nice to have the popup remain open even after you have killed some window.

**Comment by wsmwk** [comment]
Confirmed, this still occurs.  Conversely, tabby does not close when closing a single tab for a window that has multiple tabs.

**Comment by Bill13579** [comment]
I've looked into this but annoyingly the browser always closes the popup when the window is switched. This can only be fixed with a change to the browser's behavior.

**Comment by wsmwk** [comment]
> I've looked into this but annoyingly the browser always closes the popup when the window is switched or closed (even if the window isn't the one where the popup is located). This can only be fixed with a change to the browser's behavior.

Thanks. 

@Bill13579 Is there a Firefox bug report to resolve the behavior that would help make this possible for the add-on?

**Comment by pmetzger** [comment]
Couldn't the popup be re-opened as a workaround?

**Comment by Bill13579** [comment]
> > I've looked into this but annoyingly the browser always closes the popup when the window is switched or closed (even if the window isn't the one where the popup is located). This can only be fixed with a change to the browser's behavior.
> 
> Thanks.
> 
> @Bill13579 Is there a Firefox bug report to resolve the behavior that would help make this possible for the add-on?



Currently I don't think there are any, but I might just open up an issue later on!



> Couldn't the popup be re-opened as a workaround?

I've tried that, but lo'and'behold! [https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/openPopup](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/openPopup)

And I quote: `You can only call this function from inside the handler for a [user action](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/User_actions).`

It's *really* annoying I know, there are a bunch of these on other apis too and while the concept isn't half-bad, I would hope that the browser is able to better detect the difference.

### Example

The popup is opened, a new window is selected. The `click` event is fired on the Tabby popup page, and Tabby can do anything requiring user action inside of here. But once the window is selected and the window is switched, Firefox shuts down the popup. The `click` event handler is now gone, and any subsequent attempts to open up the popup automatically back up is denied.

**Comment by pmetzger** [comment]
@Bill13579 Is my idea above impossible?

**Comment by Bill13579** [comment]
> @Bill13579 Is my idea above impossible?

It will take a while, it's better than using a popup in terms of API restrictions, but there are still some things that will needs workarounds. Also it has to be integrated into the existing feature set somehow, right now in the dev builds I have it set to pressing Ctrl+Shift+P to toggle between different view modes.

**Comment by pmetzger** [comment]
So you already have something like this? How do I load a dev build to try it?

**Comment by Bill13579** [comment]
> So you already have something like this? How do I load a dev build to try it?

https://github.com/Bill13579/tabby/actions/runs/3165464432 Download the artifact and use the instructions on the README to load it into Firefox

**Comment by pmetzger** [comment]
Thank you! Should the README note the existence of the dev builds?

**Comment by pmetzger** [comment]
Wow! I'm trying out the "tabs listed in a window" feature now and dare I say it's life changing even already? I just managed to dump a half dozen unneeded windows full of stuff I didn't want because I could just scroll through the full list. You need a release with this thing!

**Comment by Bill13579** [comment]
Woah, that's awesome! Now I'm super excited, hopefully the final touches don't take too long.

**Comment by pmetzger** [comment]
I have some ideas on some fit and finish stuff that will make it easier to use for someone trying to weed out unused windows and tabs etc., but I'm going to wait to bombard you with them until there's a release.

**Comment by wsmwk** [comment]
The artifact didn't work for me. I installed the zip renamed to xpi in the Firefox developer edition. Add-ons manager states last update of the addon as November 15, 2022

**Comment by pmetzger** [comment]
FWIW, it would really be nice to get this into a release.

**Comment by wsmwk** [comment]
> FWIW, it would really be nice to get this into a release.

Yes, this alone is worth a new release. @Bill13579 what final touches are needed?

@pmetzger can you post somewhere, or email me, a working version?

**Comment by pmetzger** [comment]
I just used the dev build.

**Comment by pmetzger** [comment]
(Unzip it, then follow the instructions in the repository README which tell you to open up about:debug, press a button, open manifest.json)

**Comment by pmetzger** [comment]
Hrm. Now I can't figure out how to get the "in window" view when running the debug version.

**Comment by pmetzger** [comment]
Never mind, it was ctrl-shift-p

**Comment by wsmwk** [comment]
thanks. I followed the directions.  I don't have the patience to try again
