### ISSUE TITLE
Improvement: Cursor selection of searched tabs

### ISSUE THREAD

**Issue by mberg2007** [Bill13579/tabby#84]
When the shortcut key to open Tabby with focus on the search field is activated (shift-control-space), the user can type in a word or part of a word to narrow down the list of tabs to only those that contain that text in the title. This is a great feature that I use all the time.

However, after having narrowed down the number of tabs to perhaps 3-5, there is no way to use cursor up or down to select one of those tabs to switch to. One has to reach out for the mouse and click the tab in the list. If you are used to similar extensions on Chrome (Tabli for example) you really miss being able to quickly cursor down once or twice and then hit enter. Using the mouse is quite a bit slower.

So I would like to ask for a feature that allows cursor up and down to be used to select from the list of tabs that have been found by searching.

**Comment by mberg2007** [comment]
Supplement: There is actually a way to make this work. If you type in some characters to search for, the results are shown in the list. If you then press enter, focus shifts down to the list of results and you can now move the cursor up and down to select the relevant tab.

So I would like to amend my original request and ask that the step to press enter in the search field can be eliminated. It doesn't seem to serve any purpose.

**Comment by Bill13579** [comment]
That's true, the arrow key can go directly to the search results; implemented in 3
