### ISSUE TITLE
Improvement: Configurable shortcut keys

### ISSUE THREAD

**Issue by mberg2007** [Bill13579/tabby#85]
There are a number of issues related to shortcut keys, including an issue where a shortcut conflicts with Bitwarden.

I'm used to a similar extension on Chrome (Tabli) where the shortcut key was Alt+Q to switch between recently used tabs (Shift-Ctrl-L in tabby). I would really appreciate a feature that would allow me to configure the shortcut key in Tabby.

I understand there may be constraints in the Firefox extensions framework that complicates this or even makes it impossible, but please give it a try anyway.

**Comment by Bill13579** [comment]
I'll add a link to it in the settings page.
