### ISSUE TITLE
[Request] Multiple tab handling

### ISSUE THREAD

**Issue by rayman89** [Bill13579/tabby#86]
Hello. Thank you so much for such wonderful add-on. I was wondering if it would be possible if you could add the possibility of selecting multiple tabs by using tab or shift+ click and allowing to re arrange the selected tabs by drag and dropping and right click to get a menu similar or if possible the same one that appears when you select multiple tabs on Firefox´s tab bar so that you can close the selected tabs, reload them,suspend/unload them etc. Thank you for your time

![image](https://user-images.githubusercontent.com/5449042/132755637-8d72c5a7-362f-4f4a-b512-0bac3479b983.png)

**Comment by Bill13579** [comment]
Hey @rayman89, it's implemented :)
(I'll open a separate issue regarding the additional context menu options, namely unload/load and reloading)

**Comment by rayman89** [comment]
Thank you so much!!
