### ISSUE TITLE
Closing

### ISSUE THREAD

**Issue by CiprianCapus** [Bill13579/tabby#87]
Some suggestion:
Keep tabby open when browser loses focus
Don't clear last search on close.

**Comment by Bill13579** [comment]
I've investigated the former quite a bit over multiple times, but I've never been able to bypass the browser's default behavior, which makes Tabby lose focus whenever the tab beneath the popup switches or when the window changes.

Not clearing is the search box is a great idea! Its been implemented in d463082ae1687ff3e6549aff534f9209b099671a
