### ISSUE TITLE
[Suggestion] Search URL too

### ISSUE THREAD

**Issue by SpitFire-666** [Bill13579/tabby#88]
(Apologies if this is a dupe)

Is it possible to have Tabby search URLs as well as tab titles? Github for example doesn't have the domain in the window title, only in the URL:

![image](https://user-images.githubusercontent.com/38451588/136475442-45165439-0221-4176-b3d6-7588023733d7.png)

Thanks!

**Comment by Bill13579** [comment]
Hey @SpitFire-666! If you click on the settings button beside the search bar and tick the option that says "Search in URLs", it should start searching in URLs

**Comment by plan5** [comment]
For those looking for an answer in 2022: The cogwheel button beside the search bar is gone but you can right click the Tabby icon in the toolbar and open Options from there.
