### ISSUE TITLE
Increase density of informations in interface

### ISSUE THREAD

**Issue by barmic** [Bill13579/tabby#9]
2 options could increase quantity of informations and allow to navigate little more quickly.

1. don't show "Window 1 current" if it's the only window
2. show the pin tab as pin (like made by tab center redux https://github.com/eoger/tabcenter-redux)

With that we can show more tab in first display.

**Comment by Bill13579** [comment]
Your suggestions are great, but I want to make the display consistent, so I won't be adding this feature.
